server:
  port: 8085

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL

  sql:
    init:
      platform: postgres
  cloud:
    aws:
      region: ${AWS_REGION:sa-east-1}
      endpoint: ${AWS_ENDPOINT_HOST:localhost}
      sqs:
        queue-name: ${SQS_INIT_PRODUCTION_URL}
      sns:
        topic-name: ${SNS_PRODUCTION_STATUS_CHANGED_ARN}
management:
  endpoints:
    web:
      exposure:
        include: health