server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
  sql:
    init:
      platform: postgres
  cloud:
    aws:
      region: ${AWS_REGION}
      endpoint: ${AWS_ENDPOINT_HOST}
      sqs:
        queue-name: ${AWS_QUEUE_NAME}
      sns:
        topic-name: ${AWS_TOPIC_NAME}
management:
  endpoints:
    web:
      exposure:
        include: health